hw03
ISoRkAI/nodejs-homework-02 pull request #2
Opened 2023-01-20 01:01 UTC by ISoRkAI

2023-01-20 09:56 UTC, KhYulian commented on server.js
> +start();
Можна використати IIFE

2023-01-20 09:58 UTC, KhYulian requested changes
Потрібні правки

2023-01-20 09:58 UTC, KhYulian commented on src/models/contacts.js
> +  }
try catch в даних функція не потрібен. Обробляйте помилки в контроллері, який їх викликає

2023-01-20 09:58 UTC, KhYulian commented on src/models/contacts.js
> +    return error;
d remove & update потрібно обробити сценарій, коли документ не було знайдено і, відповідно не було видалено чи оновлено

2023-01-21 18:06 UTC, ISoRkAI commented on server.js
> +start();
Використав

2023-01-21 18:06 UTC, ISoRkAI commented on src/models/contacts.js
> +  }
Прибрав

2023-01-21 18:06 UTC, ISoRkAI commented on src/models/contacts.js
> +    return error;
Добавив

2023-01-21 18:10 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-21 18:11 UTC, merged