HW-04
ISoRkAI/nodejs-homework-02 pull request #3
Opened 2023-01-29 22:03 UTC by ISoRkAI

Просьба проверить

2023-01-30 04:35 UTC, KhYulian requested changes
Потрібні правки

2023-01-30 04:35 UTC, KhYulian commented on src/helpers/apiHelpers.js
> +  }
потрібно додати дефолтну відповідь, якщо перевірка не спрацює

2023-01-30 04:35 UTC, KhYulian commented on src/helpers/apiHelpers.js
> +  }
У вашому випадку можна взагалі забрпти цю перевірку, натомість написати 
return res.status(error.status || 500).json({ message: error.message || "Internal server error"});

2023-01-30 04:35 UTC, KhYulian commented on src/helpers/errors.js
> +}
Трохи забагато у вас помилок) LoginAuthError LogoutUnauthorizedError CurrentUserUnauthorizedError це одне і те саме - зробіть один клас AuthorizationError, інші класи теж можна спростити

2023-01-30 04:36 UTC, KhYulian requested changes
Потрібні правки

2023-01-30 04:36 UTC, KhYulian commented on src/routes/api/authUser.js
> +  }
Усю логіку, пов'язану із валідацією, здійснюйте в окремій middleware, яка спрацьовуватиме перед контроллером

2023-01-30 04:36 UTC, KhYulian commented on src/routes/api/authUser.js
> +  }
Стомується усього коду, звісно)

2023-01-31 21:54 UTC, ISoRkAI commented on src/helpers/apiHelpers.js
> +  }
Прибрав зайві еррор

2023-01-31 21:55 UTC, ISoRkAI commented on src/routes/api/authUser.js
> +  }
додав валідацію в роутер

2023-02-01 07:47 UTC, KhYulian approved these changes
Чудова робота :)

2023-02-01 07:48 UTC, merged