hw-05
ISoRkAI/nodejs-homework-02 pull request #4
Opened 2023-02-03 16:32 UTC by ISoRkAI

Просьба проверить

2023-02-03 17:19 UTC, KhYulian requested changes
Потрібна правка

2023-02-03 17:19 UTC, KhYulian commented on app.js
> +app.use('/avatars', express.static('./src/public/avatars'));
app.use(express.static('public'));

2023-02-03 21:02 UTC, ISoRkAI commented on app.js
> +app.use('/avatars', express.static('./src/public/avatars'));
исправил, только не могу открыть в браузере.
так не работает app.use(express.static('public'));
так тоже не работает app.use('/avatars', express.static('public'));
так работало app.use('/avatars', express.static('./src/public/avatars'));

2023-02-04 06:44 UTC, KhYulian commented on app.js
> +app.use('/avatars', express.static('./src/public/avatars'));
public не має бути в src, а в кореневій папці)

2023-02-04 06:45 UTC, KhYulian commented on app.js
> +app.use('/avatars', express.static('./src/public/avatars'));
тоді має працювати як слід

2023-02-04 06:45 UTC, KhYulian commented on app.js
> +app.use('/avatars', express.static('./src/public/avatars'));
щоб побачити фото потрібно буде ввести localhost:PORT/avatars/AVATARFILENAME

2023-02-04 09:21 UTC, ISoRkAI commented on app.js
> +app.use('/avatars', express.static('./src/public/avatars'));
сделано. спасибо за подсказку

2023-02-04 11:44 UTC, KhYulian approved these changes
Чудова робота :)

2023-02-04 11:44 UTC, merged